on:
  push:
    branches:
      - master
jobs:
  #build:
  #uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  visual-keymap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: resvg
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install pipx
        uses: CfirTsabari/actions-pipx@v1
      - name: Run something using pipx
        run: pipx run keymap-drawer parse -c 10 -z ./config/corne.keymap >./visual/corne_keymap.yaml
      - name: transform keymap
        run: deno run --allow-read --allow-write ./visual/transformKeymap.ts
      - name: draw keymap
        run: pipx run keymap-drawer draw ./visual/transformed_keymap.yaml >./visual/keymap.svg
      - run: cat ./visual/keymap.svg
      - name: render svg
        run: |
          resvg ./assets/keymap.svg ./assets/keymap.png --background=#fff

      - name: GIT Commit Build Artifacts
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "FalkZ"
          git config --global user.email "FalkZ@users.noreply.github.com"
          git checkout visual
          git add ./visual/keymap.png
          git add ./visual/keymap.svg
          git commit -m "Update visual keymap"
          git push -f
